import os
import shlex
import subprocess
import sys
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime
from pathlib import Path

from daily_briefing.config import parse_env_file
from daily_briefing.reports import REPORTS

from app.config import get_settings
from app.store import create_run_log, finish_run_log


# Manual "run now" requests execute here so the HTTP request returns immediately
# instead of blocking the worker for the full subprocess duration.
_RUN_EXECUTOR = ThreadPoolExecutor(max_workers=2, thread_name_prefix="manual-run")


COMMON_KEYS = {
    "FEISHU_WEBHOOK",
    "FEISHU_WEBHOOKS",
    "WECHAT_WORK_WEBHOOK",
    "WECHAT_WORK_WEBHOOKS",
    "PUSH_TARGETS",
    "SEND_AT_LOCAL",
    "FEISHU_IMAGE_DAILY_ENABLED",
}

COOKIE_INPUTS = {
    "weibo": ("WEIBO_COOKIE", "WEIBO_COOKIE_FILE"),
    "zsxq": ("ZSXQ_COOKIE", "ZSXQ_COOKIE_FILE"),
}


def quote_env_value(value: str) -> str:
    return shlex.quote(str(value))


def write_secret_file(subscription_id: int, report_type: str, key: str, value: str) -> Path:
    settings = get_settings()
    settings.env_dir.mkdir(parents=True, exist_ok=True)
    path = settings.env_dir / f"subscription_{subscription_id}_{report_type}_{key.lower()}.txt"
    path.write_text(value.strip() + "\n", encoding="utf-8")
    path.chmod(0o600)
    return path


def build_subscription_env(subscription: dict) -> tuple[Path, dict]:
    settings = get_settings()
    report = REPORTS[subscription["report_type"]]
    base_values = parse_env_file(report.default_env)
    values = dict(base_values)
    values.update(
        {
            "FEISHU_WEBHOOK": subscription.get("feishu_webhook", ""),
            "FEISHU_WEBHOOKS": "",
            "WECHAT_WORK_WEBHOOK": "",
            "WECHAT_WORK_WEBHOOKS": "",
            "PUSH_TARGETS": "primary",
            "SEND_AT_LOCAL": "",
        }
    )
    config_values = {key: str(value) for key, value in subscription.get("config", {}).items() if value is not None}
    cookie_input = COOKIE_INPUTS.get(subscription["report_type"])
    if cookie_input:
        cookie_key, cookie_file_key = cookie_input
        raw_cookie = config_values.pop(cookie_key, "").strip()
        if raw_cookie:
            cookie_path = write_secret_file(subscription["id"], subscription["report_type"], cookie_key, raw_cookie)
            config_values[cookie_file_key] = str(cookie_path)
    values.update(config_values)

    settings.env_dir.mkdir(parents=True, exist_ok=True)
    env_path = settings.env_dir / f"subscription_{subscription['id']}_{subscription['report_type']}.env"
    lines = [
        "# Generated by Daily Briefing private dashboard.",
        "# Do not commit this file.",
    ]
    for key in sorted(values):
        lines.append(f"{key}={quote_env_value(values[key])}")
    env_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    env_path.chmod(0o600)
    return env_path, values


def run_subscription(
    subscription: dict,
    *,
    render_only: bool = False,
    digest_date: str = "",
    run_id: int | None = None,
) -> dict:
    settings = get_settings()
    report_type = subscription["report_type"]
    env_path, env_values = build_subscription_env(subscription)
    settings.output_dir.mkdir(parents=True, exist_ok=True)

    output_path = ""
    cmd = [
        sys.executable,
        "-m",
        "daily_briefing.cli",
        "run",
        report_type,
        "--env",
        str(env_path),
        "--send-at",
        "",
    ]
    if digest_date:
        cmd.extend(["--date", digest_date])
    if render_only:
        output_path = str(
            settings.output_dir
            / f"subscription_{subscription['id']}_{report_type}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.png"
        )
        cmd.extend(["--render-only", "--output", output_path])

    if run_id is None:
        run_id = create_run_log(subscription["id"], report_type, "running", output_path=output_path)
    env = os.environ.copy()
    env.update(env_values)
    env["PYTHONPATH"] = f"{settings.project_path}:{settings.project_path / 'apps/api'}:{env.get('PYTHONPATH', '')}"
    try:
        completed = subprocess.run(
            cmd,
            cwd=settings.project_path,
            env=env,
            text=True,
            capture_output=True,
            timeout=60 * 60,
        )
    except Exception as exc:
        message = str(exc)
        finish_run_log(run_id, "failed", message=message, output_path=output_path)
        return {"id": run_id, "status": "failed", "message": message, "output_path": output_path}

    message = "\n".join(part for part in (completed.stdout.strip(), completed.stderr.strip()) if part).strip()
    if completed.returncode == 0:
        finish_run_log(run_id, "success", message=message[-4000:], output_path=output_path)
        return {"id": run_id, "status": "success", "message": message, "output_path": output_path}

    message = f"exit={completed.returncode}\n{message}".strip()
    finish_run_log(run_id, "failed", message=message[-4000:], output_path=output_path)
    return {"id": run_id, "status": "failed", "message": message, "output_path": output_path}


def _safe_run(subscription: dict, render_only: bool, digest_date: str, run_id: int) -> None:
    try:
        run_subscription(subscription, render_only=render_only, digest_date=digest_date, run_id=run_id)
    except Exception as exc:  # pragma: no cover - defensive; run_subscription already handles most errors
        finish_run_log(run_id, "failed", message=str(exc))


def submit_run(subscription: dict, *, render_only: bool = False, digest_date: str = "") -> int:
    """Create a run log and execute the report in the background.

    Returns the run_id immediately so callers (the HTTP handler) don't block on
    the subprocess. The caller can poll run log status to track completion.
    """
    run_id = create_run_log(subscription["id"], subscription["report_type"], "running")
    _RUN_EXECUTOR.submit(_safe_run, subscription, render_only, digest_date, run_id)
    return run_id


def run_hot_collector(subscription: dict) -> dict:
    """Run a report script in hot-collect-only mode.

    Used by the scheduler to periodically snapshot data (e.g. Weibo hot search)
    that the daily report later aggregates. Successful runs are intentionally
    not written to run_logs to avoid flooding the dashboard; only failures are.
    """
    settings = get_settings()
    report_type = subscription["report_type"]
    env_path, env_values = build_subscription_env(subscription)
    cmd = [
        sys.executable,
        "-m",
        "daily_briefing.cli",
        "run",
        report_type,
        "--env",
        str(env_path),
        "--send-at",
        "",
    ]
    env = os.environ.copy()
    env.update(env_values)
    env["COLLECT_HOT_ONLY"] = "1"
    env["RENDER_ONLY"] = ""
    env["PYTHONPATH"] = f"{settings.project_path}:{settings.project_path / 'apps/api'}:{env.get('PYTHONPATH', '')}"
    try:
        completed = subprocess.run(
            cmd,
            cwd=settings.project_path,
            env=env,
            text=True,
            capture_output=True,
            timeout=10 * 60,
        )
    except Exception as exc:
        run_id = create_run_log(subscription["id"], f"{report_type}:collector", "failed")
        finish_run_log(run_id, "failed", message=str(exc))
        return {"status": "failed", "message": str(exc)}

    if completed.returncode == 0:
        return {"status": "success", "message": completed.stdout.strip()[-2000:]}

    message = "\n".join(part for part in (completed.stdout.strip(), completed.stderr.strip()) if part).strip()
    message = f"exit={completed.returncode}\n{message}".strip()
    run_id = create_run_log(subscription["id"], f"{report_type}:collector", "failed")
    finish_run_log(run_id, "failed", message=message[-4000:])
    return {"status": "failed", "message": message}
