import os
import shlex
import subprocess
import sys
from datetime import datetime
from pathlib import Path

from daily_briefing.config import parse_env_file
from daily_briefing.reports import REPORTS

from app.config import get_settings
from app.store import create_run_log, finish_run_log


COMMON_KEYS = {
    "FEISHU_WEBHOOK",
    "WECHAT_WORK_WEBHOOK",
    "PUSH_TARGETS",
    "SEND_AT_LOCAL",
    "FEISHU_IMAGE_DAILY_ENABLED",
}


def quote_env_value(value: str) -> str:
    return shlex.quote(str(value))


def build_subscription_env(subscription: dict) -> tuple[Path, dict]:
    settings = get_settings()
    report = REPORTS[subscription["report_type"]]
    base_values = parse_env_file(report.default_env)
    values = dict(base_values)
    values.update(
        {
            "FEISHU_WEBHOOK": subscription.get("feishu_webhook", ""),
            "WECHAT_WORK_WEBHOOK": subscription.get("wechat_work_webhook", ""),
            "PUSH_TARGETS": subscription.get("push_targets") or "primary",
            "SEND_AT_LOCAL": "",
        }
    )
    values.update({key: str(value) for key, value in subscription.get("config", {}).items() if value is not None})

    settings.env_dir.mkdir(parents=True, exist_ok=True)
    env_path = settings.env_dir / f"subscription_{subscription['id']}_{subscription['report_type']}.env"
    lines = [
        "# Generated by Daily Briefing private dashboard.",
        "# Do not commit this file.",
    ]
    for key in sorted(values):
        lines.append(f"{key}={quote_env_value(values[key])}")
    env_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    env_path.chmod(0o600)
    return env_path, values


def run_subscription(subscription: dict, *, render_only: bool = False, digest_date: str = "") -> dict:
    settings = get_settings()
    report_type = subscription["report_type"]
    env_path, env_values = build_subscription_env(subscription)
    settings.output_dir.mkdir(parents=True, exist_ok=True)

    output_path = ""
    cmd = [
        sys.executable,
        "-m",
        "daily_briefing.cli",
        "run",
        report_type,
        "--env",
        str(env_path),
        "--send-at",
        "",
        "--push-targets",
        subscription.get("push_targets") or "primary",
    ]
    if digest_date:
        cmd.extend(["--date", digest_date])
    if render_only:
        output_path = str(
            settings.output_dir
            / f"subscription_{subscription['id']}_{report_type}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.png"
        )
        cmd.extend(["--render-only", "--output", output_path])

    run_id = create_run_log(subscription["id"], report_type, "running", output_path=output_path)
    env = os.environ.copy()
    env.update(env_values)
    env["PYTHONPATH"] = f"{settings.project_path}:{settings.project_path / 'apps/api'}:{env.get('PYTHONPATH', '')}"
    try:
        completed = subprocess.run(
            cmd,
            cwd=settings.project_path,
            env=env,
            text=True,
            capture_output=True,
            timeout=60 * 60,
        )
    except Exception as exc:
        message = str(exc)
        finish_run_log(run_id, "failed", message=message, output_path=output_path)
        return {"id": run_id, "status": "failed", "message": message, "output_path": output_path}

    message = "\n".join(part for part in (completed.stdout.strip(), completed.stderr.strip()) if part).strip()
    if completed.returncode == 0:
        finish_run_log(run_id, "success", message=message[-4000:], output_path=output_path)
        return {"id": run_id, "status": "success", "message": message, "output_path": output_path}

    message = f"exit={completed.returncode}\n{message}".strip()
    finish_run_log(run_id, "failed", message=message[-4000:], output_path=output_path)
    return {"id": run_id, "status": "failed", "message": message, "output_path": output_path}
